// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Opcode.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Opcode.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {

namespace {

const ::google::protobuf::EnumDescriptor* Opcode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Opcode_2eproto() {
  protobuf_AddDesc_Opcode_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Opcode.proto");
  GOOGLE_CHECK(file != NULL);
  Opcode_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Opcode_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_Opcode_2eproto() {
}

void protobuf_AddDesc_Opcode_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014Opcode.proto\022\002pb*\241\001\n\006Opcode\022\025\n\021SMSG_UN"
    "KONW_ERROR\020\001\022\023\n\017CMSG_ENTER_ROOM\020\002\022\023\n\017SMS"
    "G_ENTER_ROOM\020\003\022\025\n\021CMSG_USER_MESSAGE\020\004\022\025\n"
    "\021SMSG_USER_MESSAGE\020\005\022\023\n\017CMSG_LEAVE_ROOM\020"
    "\006\022\023\n\017SMSG_LEAVE_ROOM\020\007", 182);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Opcode.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Opcode_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Opcode_2eproto {
  StaticDescriptorInitializer_Opcode_2eproto() {
    protobuf_AddDesc_Opcode_2eproto();
  }
} static_descriptor_initializer_Opcode_2eproto_;
const ::google::protobuf::EnumDescriptor* Opcode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Opcode_descriptor_;
}
bool Opcode_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
